project_name: fragments

dist: dist

gomod:
  proxy: true

builds:
  - id: fragments
    dir: fragments
    main: .
    binary: fragments
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    mod_timestamp: "{{ .CommitDate }}"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    builds:
      - fragments
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"
      - "^ci:"
      - "^wip:"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: bluefalconhd
    name: fragments
  draft: false
  prerelease: auto
