# fragments configuration

# directory where types of fragments are stored
fragments: "fragment"
pages: "page"

# default page template
page_template: "fragment/page.frag"

# build directory
build: "build"

