# fragments configuration

# directory where types of fragments are stored
fragments: "fragment"
pages: "page"

# directory where extra files (stylesheets, scripts, images) are stored to be copied to the output directory
include: "include"

# directory where resulting pages are stored
build: "build"
